version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: tape
    versions:
    - 5.2.1
  - dependency-name: "@babel/register"
    versions:
    - 7.13.0
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.16
    - 7.12.17
    - 7.13.0
